-- 20160719

-- This file is derived from the IANA Language Subtag Registry

DROP TABLE IF EXISTS isoTagMap;
CREATE TABLE isoTagMap (
	iso TEXT PRIMARY KEY,
	iana TEXT
);

DROP TABLE IF EXISTS zlsSubtagData;
CREATE TABLE zlsSubtagData (
	id INTEGER PRIMARY KEY,
	value TEXT
);
INSERT INTO "zlsSubtagData" VALUES(6,'language');
INSERT INTO "zlsSubtagData" VALUES(16621,'region');
INSERT INTO "zlsSubtagData" VALUES(16,'Latn');
INSERT INTO "zlsSubtagData" VALUES(179,'Jpan');
INSERT INTO "zlsSubtagData" VALUES(94,'en');
INSERT INTO "zlsSubtagData" VALUES(95,'English');
INSERT INTO "zlsSubtagData" VALUES(17130,'US');
INSERT INTO "zlsSubtagData" VALUES(17131,'United States');
INSERT INTO "zlsSubtagData" VALUES(16805,'GB');
INSERT INTO "zlsSubtagData" VALUES(16806,'United Kingdom');
INSERT INTO "zlsSubtagData" VALUES(114,'fr');
INSERT INTO "zlsSubtagData" VALUES(115,'French');
INSERT INTO "zlsSubtagData" VALUES(16798,'FR');
INSERT INTO "zlsSubtagData" VALUES(16799,'France');
INSERT INTO "zlsSubtagData" VALUES(178,'ja');
INSERT INTO "zlsSubtagData" VALUES(180,'Japanese');
INSERT INTO "zlsSubtagData" VALUES(16883,'JP');
INSERT INTO "zlsSubtagData" VALUES(16884,'Japan');

DROP TABLE IF EXISTS zlsSubtags;
CREATE TABLE zlsSubtags (
	seq INTEGER PRIMARY KEY,
	subtag INT,
	tag INT,
	type INT,
	suppressscript INT,
	scope INT,
	preferredvalue INT,
	macrolanguage INT,
	added INT,
	description INT,
	deprecated INT,
	comment INT,
	prefix INT
);
INSERT INTO "zlsSubtags" VALUES(38,94,NULL,6,16,NULL,NULL,NULL,NULL,95,NULL,NULL,NULL);
INSERT INTO "zlsSubtags" VALUES(9012,17130,NULL,16621,NULL,NULL,NULL,NULL,NULL,17131,NULL,NULL,NULL);
INSERT INTO "zlsSubtags" VALUES(48,114,NULL,6,16,NULL,NULL,NULL,NULL,115,NULL,NULL,NULL);
INSERT INTO "zlsSubtags" VALUES(8846,16798,NULL,16621,NULL,NULL,NULL,NULL,NULL,16799,NULL,NULL,NULL);
INSERT INTO "zlsSubtags" VALUES(77,178,NULL,6,179,NULL,NULL,NULL,NULL,180,NULL,NULL,NULL);
INSERT INTO "zlsSubtags" VALUES(8887,16883,NULL,16621,NULL,NULL,NULL,NULL,NULL,16884,NULL,NULL,NULL);
INSERT INTO "zlsSubtags" VALUES(8849,16805,NULL,16621,NULL,NULL,NULL,NULL,NULL,16806,NULL,NULL,NULL);
